### ISSUE TITLE
CMakeLists.txt missing from root directory of cvBlob

### ISSUE THREAD

**Issue by tiltit** [Steelskin/cvblob#1]
Hi, I wanted to add cvBlob as a submodule to one of my projects. I then noticed that CMakeLists.txt is missing from the git repository.

**Comment by Steelskin** [comment]
Hi,
I no longer actively maintain cvBlob as this is a project I was working on for my previous employer.
I actually never added the CMake files and forgot to remove the references in the README file from the project I forked, sorry about that! I will welcome pull requests to add these. Looking back, it appears a bunch of old references remained around too.

**Comment by xunshuidezhu** [comment]
so, how to build the project

**Comment by xunshuidezhu** [comment]
ok, i find it

**Comment by Steelskin** [comment]
This was fixed in #8
