### ISSUE TITLE
fatal error: cvblob.h: No such file or directory  #include <cvblob.h>

### ISSUE THREAD

**Issue by ghost** [Steelskin/cvblob#3]
While installing cvblob the title error pops up in ubuntu terminal. I have cross-checked, there is no such header file in the zip file.
Am I missing something? Is there any alternative?

**Comment by ghost** [comment]
First, i think you need to download again cvblob source file, then extract it. Second, open terminal and run  some command : cd cvblob 
mkdir build
cmake ../
sudo make install
cd build

**Comment by Steelskin** [comment]
This should now work if you configure the compiler include path. I would suggest building with Meson if you want to have a pkgconfig that will take of it for you.
