### ISSUE TITLE
Mistake in calculating area

### ISSUE THREAD

**Issue by farzadbaghbani** [Steelskin/cvblob#6]
https://github.com/Steelskin/cvblob/blob/c8448e2430bcd200d5c0e38fea10be71ef8bb9eb/cvBlob/cvb_track.cpp#L251

 unsigned int a = (a_track->maxx - a_track->minx + 1) * (a_track->maxy - a_track->miny + 1);

**Comment by Steelskin** [comment]
The tracking code was never ported from the original repository. This is tracked in #2
